name: Build Container Image

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE_REPO: ${{ vars.IMAGE_REPO }}
  IMAGE_TAG: latest

jobs:
  build:
    name: Build Container Image
    runs-on: self-hosted
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v2
        with:
          cache: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      
      - name: Login to Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ vars.DOCKER_USERNAME }} --password-stdin ${{ vars.IMAGE_REPO }}

      - name: Build and push image  
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 --push  -f build/regulaway/Dockerfile -t $IMAGE_REPO/regulaway:$IMAGE_TAG .
